/**
 * PR A géo — Principales villes par pays (codes ISO 3166-1 alpha-2).
 *
 * Référentiel STATIQUE versionné : aucune API, aucune dépendance. Ce module
 * n'est consommé QUE par `import()` dynamique (country-city-fields.tsx) : il
 * vit dans un chunk séparé et n'alourdit pas le bundle initial.
 *
 * Couverture : TOUS les pays et territoires HABITÉS de la liste ISO —
 * capitale/agglomération principale + villes majeures (3 à 8 pour un pays
 * ordinaire, listes enrichies pour les pays prioritaires de la diaspora
 * KASSALAFAM). Il s'agit volontairement des PRINCIPALES villes (l'interface
 * le dit) : tout pays propose toujours « Autre ville » avec saisie manuelle.
 * Les territoires INHABITÉS (voir UNINHABITED_TERRITORIES) n'ont pas de
 * liste : l'interface passe directement en saisie libre, sans inventer de
 * localité.
 *
 * Provenance / licence : compilation ORIGINALE rédigée pour KASSALAFAM à
 * partir de connaissances géographiques générales (capitales et grandes
 * villes, référentiel ISO 3166-1). Aucun dataset tiers n'a été copié :
 * aucune licence externe ne s'applique, le fichier suit la licence du projet.
 *
 * Les libellés sont les valeurs réellement stockées dans `profiles.city`
 * (dont « Douala », « Yaoundé » déjà en base) — exonymes français usuels.
 */

/**
 * Territoires ISO sans population permanente (ou sans localité civile
 * identifiable) : aucune liste de villes — saisie libre uniquement.
 */
export const UNINHABITED_TERRITORIES: ReadonlySet<string> = new Set([
  "AQ", // Antarctique
  "BV", // Île Bouvet
  "GS", // Géorgie du Sud-et-les îles Sandwich du Sud
  "HM", // Îles Heard-et-MacDonald
  "IO", // Territoire britannique de l'océan Indien (base militaire uniquement)
  "TF", // Terres australes françaises (bases scientifiques)
  "UM", // Îles mineures éloignées des États-Unis
]);

export const CITIES_FR: Record<string, readonly string[]> = {
  AD: ["Andorre-la-Vieille", "Escaldes-Engordany", "Encamp", "La Massana"],
  AE: ["Dubaï", "Abou Dabi", "Charjah", "Al-Aïn", "Ajman", "Ras el Khaïmah"],
  AF: ["Kaboul", "Kandahar", "Hérat", "Mazar-e Charif", "Jalalabad", "Kunduz"],
  AG: ["Saint John’s", "All Saints", "Liberta"],
  AI: ["The Valley", "Blowing Point"],
  AL: ["Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Korçë"],
  AM: ["Erevan", "Gyumri", "Vanadzor", "Vagharchapat"],
  AO: ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango", "Malanje"],
  AR: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "Mar del Plata",
    "Salta",
  ],
  AS: ["Pago Pago", "Tafuna"],
  AT: ["Vienne", "Graz", "Linz", "Salzbourg", "Innsbruck", "Klagenfurt"],
  AU: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adélaïde",
    "Canberra",
    "Gold Coast",
    "Hobart",
  ],
  AW: ["Oranjestad", "San Nicolas"],
  AX: ["Mariehamn"],
  AZ: ["Bakou", "Gandja", "Soumgaït", "Mingatchevir"],
  BA: ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
  BB: ["Bridgetown", "Speightstown", "Oistins"],
  BD: ["Dacca", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  BE: [
    "Bruxelles",
    "Anvers",
    "Gand",
    "Charleroi",
    "Liège",
    "Bruges",
    "Namur",
    "Louvain",
    "Mons",
    "Malines",
  ],
  BF: [
    "Ouagadougou",
    "Bobo-Dioulasso",
    "Koudougou",
    "Banfora",
    "Ouahigouya",
    "Kaya",
    "Tenkodogo",
    "Fada N’Gourma",
    "Dédougou",
    "Dori",
  ],
  BG: ["Sofia", "Plovdiv", "Varna", "Bourgas", "Roussé"],
  BH: ["Manama", "Riffa", "Muharraq"],
  BI: ["Gitega", "Bujumbura", "Ngozi", "Rumonge"],
  BJ: [
    "Cotonou",
    "Porto-Novo",
    "Parakou",
    "Abomey-Calavi",
    "Djougou",
    "Bohicon",
    "Natitingou",
    "Abomey",
    "Lokossa",
    "Ouidah",
  ],
  BL: ["Gustavia"],
  BM: ["Hamilton", "Saint George’s"],
  BN: ["Bandar Seri Begawan", "Kuala Belait", "Seria"],
  BO: [
    "La Paz",
    "Santa Cruz de la Sierra",
    "Cochabamba",
    "Sucre",
    "El Alto",
    "Oruro",
  ],
  BQ: ["Kralendijk", "Oranjestad", "The Bottom"],
  BR: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
  ],
  BS: ["Nassau", "Freeport", "West End"],
  BT: ["Thimphou", "Phuntsholing", "Paro"],
  BW: ["Gaborone", "Francistown", "Molepolole", "Maun"],
  BY: ["Minsk", "Homiel", "Moguilev", "Vitebsk", "Hrodna", "Brest"],
  BZ: ["Belize City", "Belmopan", "San Ignacio", "Orange Walk"],
  CA: [
    "Toronto",
    "Montréal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Québec",
    "Winnipeg",
    "Hamilton",
    "Gatineau",
    "Laval",
    "Halifax",
    "Sherbrooke",
    "Trois-Rivières",
  ],
  CC: ["West Island", "Bantam"],
  CD: [
    "Kinshasa",
    "Lubumbashi",
    "Mbuji-Mayi",
    "Kananga",
    "Kisangani",
    "Bukavu",
    "Goma",
    "Likasi",
    "Kolwezi",
    "Tshikapa",
    "Matadi",
    "Mbandaka",
    "Uvira",
    "Bunia",
    "Kikwit",
  ],
  CF: ["Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar"],
  CG: [
    "Brazzaville",
    "Pointe-Noire",
    "Dolisie",
    "Nkayi",
    "Ouesso",
    "Owando",
    "Impfondo",
    "Madingou",
    "Sibiti",
    "Kinkala",
  ],
  CH: ["Zurich", "Genève", "Bâle", "Lausanne", "Berne", "Winterthour", "Lucerne"],
  CI: [
    "Abidjan",
    "Yamoussoukro",
    "Bouaké",
    "Daloa",
    "San-Pédro",
    "Korhogo",
    "Man",
    "Divo",
    "Gagnoa",
    "Abengourou",
    "Anyama",
    "Séguéla",
    "Bondoukou",
    "Odienné",
    "Grand-Bassam",
  ],
  CK: ["Avarua"],
  CL: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "Antofagasta",
    "Viña del Mar",
    "Temuco",
  ],
  CM: [
    "Douala",
    "Yaoundé",
    "Bafoussam",
    "Bamenda",
    "Garoua",
    "Maroua",
    "Ngaoundéré",
    "Bertoua",
    "Ebolowa",
    "Buea",
    "Limbé",
    "Kumba",
    "Kribi",
    "Edéa",
    "Foumban",
    "Dschang",
    "Nkongsamba",
    "Mbouda",
    "Sangmélima",
    "Garoua-Boulaï",
  ],
  CN: [
    "Pékin",
    "Shanghai",
    "Canton",
    "Shenzhen",
    "Chengdu",
    "Chongqing",
    "Tianjin",
    "Wuhan",
    "Xi’an",
    "Hangzhou",
  ],
  CO: [
    "Bogota",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Carthagène",
    "Cúcuta",
    "Bucaramanga",
  ],
  CR: ["San José", "Alajuela", "Cartago", "Heredia", "Liberia"],
  CU: ["La Havane", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara"],
  CV: ["Praia", "Mindelo", "Santa Maria", "Assomada"],
  CW: ["Willemstad"],
  CX: ["Flying Fish Cove"],
  CY: ["Nicosie", "Limassol", "Larnaca", "Paphos", "Famagouste"],
  CZ: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc"],
  DE: [
    "Berlin",
    "Hambourg",
    "Munich",
    "Cologne",
    "Francfort-sur-le-Main",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
    "Brême",
    "Dresde",
    "Hanovre",
    "Nuremberg",
    "Bonn",
  ],
  DJ: ["Djibouti", "Ali Sabieh", "Tadjourah", "Obock", "Dikhil"],
  DK: ["Copenhague", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  DM: ["Roseau", "Portsmouth", "Marigot"],
  DO: [
    "Saint-Domingue",
    "Santiago de los Caballeros",
    "La Romana",
    "San Pedro de Macorís",
    "Puerto Plata",
  ],
  DZ: [
    "Alger",
    "Oran",
    "Constantine",
    "Annaba",
    "Blida",
    "Batna",
    "Sétif",
    "Djelfa",
    "Sidi Bel Abbès",
    "Biskra",
    "Tébessa",
    "Tlemcen",
    "Béjaïa",
    "Tizi Ouzou",
  ],
  EC: ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala"],
  EE: ["Tallinn", "Tartu", "Narva", "Pärnu"],
  EG: [
    "Le Caire",
    "Alexandrie",
    "Gizeh",
    "Charm el-Cheikh",
    "Louxor",
    "Assouan",
    "Port-Saïd",
    "Suez",
  ],
  EH: ["Laâyoune", "Dakhla", "Smara"],
  ER: ["Asmara", "Keren", "Massaoua", "Assab"],
  ES: [
    "Madrid",
    "Barcelone",
    "Valence",
    "Séville",
    "Saragosse",
    "Malaga",
    "Bilbao",
    "Palma",
    "Grenade",
  ],
  ET: ["Addis-Abeba", "Dire Dawa", "Mekele", "Gondar", "Awasa", "Bahir Dar"],
  FI: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku"],
  FJ: ["Suva", "Nadi", "Lautoka", "Labasa"],
  FK: ["Stanley"],
  FM: ["Palikir", "Weno", "Kolonia"],
  FO: ["Tórshavn", "Klaksvík"],
  FR: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Montpellier",
    "Strasbourg",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Toulon",
    "Saint-Étienne",
    "Le Havre",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
  ],
  GA: [
    "Libreville",
    "Port-Gentil",
    "Franceville",
    "Oyem",
    "Moanda",
    "Lambaréné",
    "Mouila",
    "Tchibanga",
    "Koulamoutou",
    "Makokou",
  ],
  GB: [
    "Londres",
    "Birmingham",
    "Manchester",
    "Leeds",
    "Glasgow",
    "Liverpool",
    "Édimbourg",
    "Bristol",
    "Sheffield",
    "Newcastle upon Tyne",
    "Cardiff",
    "Belfast",
    "Nottingham",
    "Leicester",
  ],
  GD: ["Saint-Georges", "Gouyave", "Grenville"],
  GE: ["Tbilissi", "Batoumi", "Koutaïssi", "Roustavi"],
  GF: [
    "Cayenne",
    "Saint-Laurent-du-Maroni",
    "Kourou",
    "Matoury",
    "Remire-Montjoly",
  ],
  GG: ["Saint-Pierre-Port", "Saint-Sampson"],
  GH: [
    "Accra",
    "Kumasi",
    "Tamale",
    "Sekondi-Takoradi",
    "Tema",
    "Cape Coast",
    "Sunyani",
    "Ho",
    "Koforidua",
    "Wa",
    "Bolgatanga",
  ],
  GI: ["Gibraltar"],
  GL: ["Nuuk", "Sisimiut", "Ilulissat", "Qaqortoq"],
  GM: ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni"],
  GN: [
    "Conakry",
    "Nzérékoré",
    "Kankan",
    "Kindia",
    "Labé",
    "Mamou",
    "Boké",
    "Faranah",
    "Kissidougou",
    "Siguiri",
  ],
  GP: [
    "Pointe-à-Pitre",
    "Les Abymes",
    "Baie-Mahault",
    "Basse-Terre",
    "Le Gosier",
  ],
  GQ: ["Malabo", "Bata", "Ebebiyín", "Mongomo"],
  GR: ["Athènes", "Thessalonique", "Le Pirée", "Patras", "Héraklion", "Larissa"],
  GT: ["Guatemala", "Mixco", "Villa Nueva", "Quetzaltenango"],
  GU: ["Hagåtña", "Dededo", "Tamuning"],
  GW: ["Bissau", "Bafatá", "Gabú", "Canchungo"],
  GY: ["Georgetown", "Linden", "New Amsterdam"],
  HK: ["Hong Kong", "Kowloon", "Tsuen Wan", "Sha Tin"],
  HN: ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso"],
  HR: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
  HT: [
    "Port-au-Prince",
    "Cap-Haïtien",
    "Gonaïves",
    "Les Cayes",
    "Jacmel",
    "Carrefour",
  ],
  HU: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Győr"],
  ID: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Medan",
    "Semarang",
    "Makassar",
    "Palembang",
    "Denpasar",
  ],
  IE: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  IL: ["Jérusalem", "Tel Aviv", "Haïfa", "Rishon LeZion", "Beer-Sheva", "Netanya"],
  IM: ["Douglas", "Ramsey", "Peel"],
  IN: [
    "New Delhi",
    "Mumbai",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Calcutta",
    "Ahmedabad",
    "Pune",
    "Jaipur",
  ],
  IQ: ["Bagdad", "Bassora", "Mossoul", "Erbil", "Kirkouk", "Nadjaf", "Souleimaniye"],
  IR: ["Téhéran", "Machhad", "Ispahan", "Chiraz", "Tabriz", "Karaj", "Qom"],
  IS: ["Reykjavik", "Kópavogur", "Hafnarfjörður", "Akureyri"],
  IT: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palerme",
    "Gênes",
    "Bologne",
    "Florence",
    "Venise",
    "Bari",
  ],
  JE: ["Saint-Hélier", "Saint-Sauveur"],
  JM: ["Kingston", "Montego Bay", "Spanish Town", "Portmore"],
  JO: ["Amman", "Zarqa", "Irbid", "Aqaba"],
  JP: [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Hiroshima",
  ],
  KE: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika"],
  KG: ["Bichkek", "Och", "Djalal-Abad", "Karakol"],
  KH: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
  KI: ["Tarawa-Sud", "Betio", "Bairiki"],
  KM: ["Moroni", "Mutsamudu", "Fomboni", "Domoni"],
  KN: ["Basseterre", "Charlestown"],
  KP: ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan"],
  KR: ["Séoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon"],
  KW: ["Koweït", "Hawalli", "Salmiya", "Al Ahmadi"],
  KY: ["George Town", "West Bay", "Bodden Town"],
  KZ: ["Almaty", "Astana", "Chymkent", "Karaganda", "Aktobe", "Taraz"],
  LA: ["Vientiane", "Savannakhet", "Paksé", "Luang Prabang"],
  LB: ["Beyrouth", "Tripoli", "Saïda", "Tyr", "Zahlé", "Jounieh"],
  LC: ["Castries", "Vieux Fort", "Gros Islet", "Soufrière"],
  LI: ["Vaduz", "Schaan", "Balzers"],
  LK: [
    "Colombo",
    "Kandy",
    "Galle",
    "Jaffna",
    "Negombo",
    "Sri Jayawardenapura Kotte",
  ],
  LR: ["Monrovia", "Gbarnga", "Buchanan", "Kakata", "Harper"],
  LS: ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse"],
  LT: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"],
  LU: ["Luxembourg", "Esch-sur-Alzette", "Differdange", "Dudelange"],
  LV: ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala"],
  LY: ["Tripoli", "Benghazi", "Misrata", "Zaouïa", "Beïda", "Sebha"],
  MA: [
    "Casablanca",
    "Rabat",
    "Fès",
    "Marrakech",
    "Tanger",
    "Salé",
    "Meknès",
    "Oujda",
    "Kénitra",
    "Agadir",
    "Tétouan",
    "Safi",
    "El Jadida",
    "Nador",
  ],
  MC: ["Monaco", "Monte-Carlo", "La Condamine", "Fontvieille"],
  MD: ["Chișinău", "Tiraspol", "Bălți", "Bender"],
  ME: ["Podgorica", "Nikšić", "Herceg Novi", "Budva", "Bar"],
  MF: ["Marigot", "Grand-Case"],
  MG: [
    "Antananarivo",
    "Toamasina",
    "Antsirabe",
    "Fianarantsoa",
    "Mahajanga",
    "Toliara",
    "Antsiranana",
  ],
  MH: ["Majuro", "Ebeye"],
  MK: ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo"],
  ML: [
    "Bamako",
    "Sikasso",
    "Ségou",
    "Mopti",
    "Koutiala",
    "Kayes",
    "Gao",
    "Kati",
    "Tombouctou",
    "Kita",
  ],
  MM: ["Rangoun", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago"],
  MN: ["Oulan-Bator", "Erdenet", "Darkhan", "Choibalsan"],
  MO: ["Macao", "Taipa", "Coloane"],
  MP: ["Saipan", "Garapan", "San Jose"],
  MQ: [
    "Fort-de-France",
    "Le Lamentin",
    "Schoelcher",
    "Le Robert",
    "Sainte-Marie",
  ],
  MR: ["Nouakchott", "Nouadhibou", "Kiffa", "Kaédi", "Rosso", "Zouérate"],
  MS: ["Brades", "Little Bay", "Salem"],
  MT: ["La Valette", "Birkirkara", "Mosta", "Qormi", "Sliema"],
  MU: [
    "Port-Louis",
    "Beau Bassin-Rose Hill",
    "Vacoas-Phoenix",
    "Curepipe",
    "Quatre Bornes",
  ],
  MV: ["Malé", "Addu", "Fuvahmulah"],
  MW: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Karonga"],
  MX: [
    "Mexico",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Cancún",
    "Mérida",
  ],
  MY: [
    "Kuala Lumpur",
    "George Town",
    "Johor Bahru",
    "Ipoh",
    "Shah Alam",
    "Kota Kinabalu",
    "Kuching",
  ],
  MZ: [
    "Maputo",
    "Matola",
    "Beira",
    "Nampula",
    "Chimoio",
    "Quelimane",
    "Tete",
    "Pemba",
  ],
  NA: ["Windhoek", "Walvis Bay", "Swakopmund", "Rundu", "Oshakati"],
  NC: ["Nouméa", "Dumbéa", "Mont-Dore", "Païta", "Koné"],
  NE: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Diffa"],
  NF: ["Kingston", "Burnt Pine"],
  NG: [
    "Lagos",
    "Abuja",
    "Kano",
    "Ibadan",
    "Port Harcourt",
    "Benin City",
    "Kaduna",
    "Enugu",
    "Aba",
    "Onitsha",
    "Warri",
    "Jos",
    "Ilorin",
    "Calabar",
    "Uyo",
  ],
  NI: ["Managua", "León", "Masaya", "Matagalpa", "Chinandega", "Granada"],
  NL: [
    "Amsterdam",
    "Rotterdam",
    "La Haye",
    "Utrecht",
    "Eindhoven",
    "Groningue",
    "Tilburg",
  ],
  NO: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Tromsø"],
  NP: ["Katmandou", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur"],
  NR: ["Yaren", "Denigomodu", "Aiwo"],
  NU: ["Alofi"],
  NZ: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin"],
  OM: ["Mascate", "Salalah", "Sohar", "Nizwa", "Sour"],
  PA: ["Panama", "San Miguelito", "Colón", "David", "La Chorrera"],
  PE: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Cusco", "Iquitos"],
  PF: ["Papeete", "Faaa", "Punaauia", "Pirae", "Mahina"],
  PG: ["Port Moresby", "Lae", "Mount Hagen", "Madang", "Goroka"],
  PH: [
    "Manille",
    "Quezon City",
    "Davao",
    "Cebu",
    "Zamboanga",
    "Caloocan",
    "Makati",
  ],
  PK: [
    "Karachi",
    "Lahore",
    "Islamabad",
    "Faisalabad",
    "Rawalpindi",
    "Peshawar",
    "Multan",
    "Quetta",
  ],
  PL: [
    "Varsovie",
    "Cracovie",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Katowice",
  ],
  PM: ["Saint-Pierre", "Miquelon"],
  PN: ["Adamstown"],
  PR: ["San Juan", "Bayamón", "Carolina", "Ponce", "Caguas"],
  PS: [
    "Gaza",
    "Ramallah",
    "Hébron",
    "Naplouse",
    "Bethléem",
    "Jéricho",
    "Khan Younès",
  ],
  PT: ["Lisbonne", "Porto", "Braga", "Coimbra", "Funchal", "Amadora", "Setúbal"],
  PW: ["Ngerulmud", "Koror", "Airai"],
  PY: ["Asuncion", "Ciudad del Este", "San Lorenzo", "Luque", "Encarnación"],
  QA: ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor"],
  RE: [
    "Saint-Denis",
    "Saint-Paul",
    "Saint-Pierre",
    "Le Tampon",
    "Saint-André",
    "Saint-Louis",
    "Le Port",
  ],
  RO: [
    "Bucarest",
    "Cluj-Napoca",
    "Timișoara",
    "Iași",
    "Constanța",
    "Craiova",
    "Brașov",
  ],
  RS: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica"],
  RU: [
    "Moscou",
    "Saint-Pétersbourg",
    "Novossibirsk",
    "Iekaterinbourg",
    "Kazan",
    "Nijni Novgorod",
    "Sotchi",
    "Vladivostok",
  ],
  RW: ["Kigali", "Huye", "Rubavu", "Musanze", "Muhanga", "Rusizi"],
  SA: ["Riyad", "Djeddah", "La Mecque", "Médine", "Dammam", "Taïf", "Tabuk"],
  SB: ["Honiara", "Auki", "Gizo"],
  SC: ["Victoria", "Anse Boileau", "Beau Vallon"],
  SD: [
    "Khartoum",
    "Omdurman",
    "Khartoum-Nord",
    "Port-Soudan",
    "Kassala",
    "El Obeid",
    "Nyala",
  ],
  SE: ["Stockholm", "Göteborg", "Malmö", "Uppsala", "Västerås", "Örebro"],
  SG: ["Singapour"],
  SH: ["Jamestown", "Georgetown", "Edinburgh of the Seven Seas"],
  SI: ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper"],
  SJ: ["Longyearbyen", "Barentsburg"],
  SK: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra"],
  SL: ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"],
  SM: ["Saint-Marin", "Serravalle", "Borgo Maggiore"],
  SN: [
    "Dakar",
    "Thiès",
    "Touba",
    "Rufisque",
    "Saint-Louis",
    "Kaolack",
    "Ziguinchor",
    "Mbour",
    "Diourbel",
    "Louga",
    "Tambacounda",
    "Kolda",
    "Fatick",
    "Kédougou",
    "Matam",
  ],
  SO: ["Mogadiscio", "Hargeisa", "Bosaso", "Kismayo", "Baidoa", "Garowe"],
  SR: ["Paramaribo", "Lelydorp", "Nieuw Nickerie"],
  SS: ["Djouba", "Malakal", "Wau", "Yei", "Aweil"],
  ST: ["São Tomé", "Santo António", "Neves", "Trindade"],
  SV: ["San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Santa Tecla"],
  SX: ["Philipsburg", "Lower Prince’s Quarter"],
  SY: ["Damas", "Alep", "Homs", "Lattaquié", "Hama", "Deir ez-Zor"],
  SZ: ["Mbabane", "Manzini", "Lobamba", "Siteki"],
  TC: ["Cockburn Town", "Providenciales"],
  TD: ["N’Djaména", "Moundou", "Sarh", "Abéché", "Kélo", "Am Timan"],
  TG: [
    "Lomé",
    "Sokodé",
    "Kara",
    "Kpalimé",
    "Atakpamé",
    "Dapaong",
    "Tsévié",
    "Aného",
    "Bassar",
    "Mango",
  ],
  TH: [
    "Bangkok",
    "Chiang Mai",
    "Nonthaburi",
    "Phuket",
    "Pattaya",
    "Hat Yai",
    "Khon Kaen",
  ],
  TJ: ["Douchanbé", "Khodjent", "Kulob", "Bokhtar"],
  TK: ["Fakaofo", "Atafu", "Nukunonu"],
  TL: ["Dili", "Baucau", "Maliana", "Suai"],
  TM: ["Achgabat", "Türkmenabat", "Daşoguz", "Mary"],
  TN: [
    "Tunis",
    "Sfax",
    "Sousse",
    "Kairouan",
    "Bizerte",
    "Gabès",
    "Ariana",
    "Gafsa",
    "Monastir",
    "Nabeul",
    "La Marsa",
    "Médenine",
  ],
  TO: ["Nuku’alofa", "Neiafu", "Haveluloto"],
  TR: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Bursa",
    "Antalya",
    "Adana",
    "Gaziantep",
    "Konya",
  ],
  TT: ["Port-d’Espagne", "San Fernando", "Chaguanas", "Arima"],
  TV: ["Funafuti"],
  TW: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Taoyuan", "Hsinchu"],
  TZ: [
    "Dar es Salam",
    "Dodoma",
    "Mwanza",
    "Arusha",
    "Zanzibar",
    "Mbeya",
    "Morogoro",
    "Tanga",
  ],
  UA: ["Kiev", "Kharkiv", "Odessa", "Dnipro", "Lviv", "Zaporijjia"],
  UG: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Mbale", "Entebbe"],
  US: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphie",
    "San Antonio",
    "San Diego",
    "Dallas",
    "Atlanta",
    "Washington",
    "Boston",
    "Miami",
    "Seattle",
    "Denver",
    "Minneapolis",
    "San Francisco",
    "Columbus",
    "Charlotte",
  ],
  UY: ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Maldonado"],
  UZ: ["Tachkent", "Samarcande", "Namangan", "Andijan", "Boukhara", "Noukous"],
  VA: ["Cité du Vatican"],
  VC: ["Kingstown", "Barrouallie", "Chateaubelair"],
  VE: [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Maracay",
    "Ciudad Guayana",
  ],
  VG: ["Road Town", "Spanish Town"],
  VI: ["Charlotte Amalie", "Christiansted", "Frederiksted"],
  VN: [
    "Hô Chi Minh-Ville",
    "Hanoï",
    "Da Nang",
    "Haïphong",
    "Cần Thơ",
    "Huê",
    "Nha Trang",
  ],
  VU: ["Port-Vila", "Luganville", "Norsup"],
  WF: ["Mata-Utu", "Leava"],
  WS: ["Apia", "Vaitele", "Faleula"],
  YE: ["Sanaa", "Aden", "Taez", "Al Hudaydah", "Ibb", "Mukalla"],
  YT: ["Mamoudzou", "Koungou", "Dzaoudzi", "Dembéni", "Sada"],
  ZA: [
    "Johannesburg",
    "Le Cap",
    "Durban",
    "Pretoria",
    "Gqeberha (Port Elizabeth)",
    "Bloemfontein",
    "East London",
    "Soweto",
    "Pietermaritzburg",
    "Polokwane",
  ],
  ZM: ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Livingstone"],
  ZW: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Masvingo"],
};

/** Principales villes d'un pays (code ISO) — vide si pays non couvert. */
export function getCitiesForCountry(code: string | null | undefined): readonly string[] {
  if (!code) return [];
  return CITIES_FR[code] ?? [];
}
